-- ============================================================
-- Mi Rendición — Schema inicial v1
-- Aplicado: 2026-06-02
-- Proyecto: jqtbtgduqzxkgubmzukg (Mi Rendición — PENTA)
-- ============================================================
-- Ver historial completo en Supabase Dashboard > Database > Migrations
-- Este archivo es copia local de referencia.
-- Para regenerar tipos: npx supabase gen types typescript --project-id jqtbtgduqzxkgubmzukg
